### ISSUE TITLE
Fix debug mode

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#135]
Currently, oreboot only builds when you include the "-p release" option. Either we should fix debug mode or remove it entirely to avoid confusion.

**Comment by sphinxc0re** [comment]
We should probably adjust the documentation accordingly

**Comment by rjoleary** [comment]
The problem is that "fixed-dtfs.dts" hard-codes the address "target/riscv64imac-unknown-none-elf/release/" in two places. If you `sed -i 's/release/debug/' fixed-dtfs.dts`, you can then build in debug mode (without "-p release").

What is the value of debug builds? The one thing I see is the output size is 9x larger!
