### ISSUE TITLE
Improve usability of layoutflash tool

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#167]
* "No such file or directory"  error message should also print the file which could not be found.
* If a file is too big to fit into the flash area, an error message should be printed. Currently, the tool silently does something bizarre.
* If two or more areas overlap, print an appropriate error message.
* Automatically calculate the offset of the area based on the sizes of the previous areas.

**Comment by doriath** [comment]
(1) seems already done, and #269 should resolve (2) and (3).

I will try doing (4) as well, but it will probably require adding some empty areas in some dts files (e.g. qemu-q35 has some gaps between areas).
