### ISSUE TITLE
open-source is NOT free. 

### ISSUE THREAD

**Issue by vivebox** [oreboot/oreboot#235]
[https://en.wikipedia.org/wiki/Sybase_Open_Watcom_Public_License](https://en.wikipedia.org/wiki/Sybase_Open_Watcom_Public_License) , the license is stronger than AGPL, but it's not free. Open-source software may have strong copyleft, but free software never.

**Comment by rminnich** [comment]
I'm a bit confused on what this all means.

**Comment by rjoleary** [comment]
Oreboot uses GPLv2.
