### ISSUE TITLE
How to enable SMP on Coreboot

### ISSUE THREAD

**Issue by fangyuanseu** [oreboot/oreboot#292]
Hi  experts,

    I'm not working on a project, run Coreboot+OPTEE+Depthcharge on Qemu-aarch64, i want to enable smp on coreboot, but have no idea how to do it, can i have some document like "porting guide" ?  Thanks in advance.

**Comment by rjoleary** [comment]
Hi, you might be in the wrong place unless you are looking for Oreboot (Coreboot written in Rust).
For Coreboot, take a look at https://www.coreboot.org/Motherboard_Porting_Guide

**Comment by fangyuanseu** [comment]
hi rjleary, 
Thanks for your replay.

**Comment by fangyuanseu** [comment]
Go to the Coreboot
