### ISSUE TITLE
x86 linker warning about data layouts

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#346]
```
warning: Linking two modules of different data layouts: '' is 'e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128' whereas 'qemu_fsp.43lg22km-cgu.2' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'
```

To reproduce:

```
cd src/mainboard/emulation/qemu-q35 && make
```

This warning shows up on all our x86 projects, but does not seem to have any noticeable effect.

The data layout comes from here: https://github.com/oreboot/oreboot/blob/master/src/custom_targets/x86_64-unknown-none.json and controls the padding/alignment of data types. It'd probably be bad if two modules with different layouts shared data types.

**Comment by fotonick** [comment]
Reproduced.

I note that they only differ with the addition of `-p270:32:32-p271:32:32-p272:64:64`. This appears to have come directly from upstream [llvm#D64931](https://reviews.llvm.org/D64931) in 2019 and applies to all x86 targets.

The [LLVM Language Reference](https://llvm.org/docs/LangRef.html#data-layout) says that these `p` directives regard to pointer sizes. The 270, 271, and 272 specify named address spaces in which the pointer sizes apply. I don't know how to use these address spaces, but it seems like the sort of thing you have to opt into(?). This suggests that the difference in data layouts is safe for us. However, it also seems better to just update our data layout to match upstream. I'll make that PR.

There's also the question of how some of our compilation units are getting our data layout and some are getting the default x86 data layout. Could the FSP binary blob be compiled with the new layout?
