### ISSUE TITLE
QEMU-FSP: Support 32-bit FSP binaries

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#357]
Oreboot is compiled for 64-bit mode. We are cheating by compiling the QEMU-FSP for 64-bit as well. Most of the FSP binaries for hardware use a 32-bit interface and we cannot recompile them.

What we need is an assembly adaptor to drop down to 32-bit mode, call FSP, then return to 64-bit mode.

The work is something like this:

1. Create a new mainboard `emulation/qemu-fsp32`
2. Research how coreboot does it
3. Write the assembly adaptor
4. Test it in qemu

**Comment by jhand2** [comment]
Looks like a can't assign issues to myself, but just wanted to mark that I'm still working on this 😄

**Comment by jhand2** [comment]
Fixed by #470
