### ISSUE TITLE
We are overusing trait objects

### ISSUE THREAD

**Issue by rminnich** [oreboot/oreboot#38]
We need to rethink our use of trait objects

sphinxc0re [1:21 AM]
I see that there are a lot of trait objects in the current codebase.

I don't think that's good. We should use generics whenever we can.
For lists of abstract objects, there is no other way though.
We couldn't do `Vec<T> where T: Driver`
because that would mean we had a list of all the same driver

rminnich [8:10 AM]
if we  used &Driver more could we then use generics instead of traits? I did get to the writeups on why generics are frequently better than traits and your point is well taken, esp. in the romstage. How can we reduce trait usage?

sphinxc0re [8:36 AM]
We would still use traits but not necessarily _trait objects_ anymore.
We can look for places in the code, where trait objects are used in a field or parameter situation. In those cases you can usually swap them out for generics that _implement that trait_
or in some rare cases just do `impl Trait`

**Comment by orangecms** [comment]
This is now obsolete. Closing thusly. :-)
