### ISSUE TITLE
Hello from the embedded WG!

### ISSUE THREAD

**Issue by andre-richter** [oreboot/oreboot#44]
Hi,

I am from Rust's [embedded devices working group](https://github.com/rust-embedded/wg) and by chance I stumbled over your interesting project here.
We're glad you find our (and Tock's) [registers](https://github.com/rust-embedded/register-rs) crate useful.
I just wanted to drop you a note that in the WG, for drivers we often use a pattern that leverages the [Deref](https://doc.rust-lang.org/core/ops/trait.Deref.html) trait that gives the code a nicer look and eases access to registers.

Example from [here](https://github.com/rust-embedded/rust-raspi3-OS-tutorials/blob/master/11_exceptions_groundwork/src/devices/hw/pl011_uart.rs):
```rust
#[allow(non_snake_case)]
#[repr(C)]
pub struct RegisterBlock {
    DR: ReadWrite<u32>,                   // 0x00
}

pub struct PL011Uart {
    base_addr: usize,
}

impl ops::Deref for PL011Uart {
    type Target = RegisterBlock;

    fn deref(&self) -> &Self::Target {
        unsafe { &*self.ptr() }
    }
}

impl PL011Uart {
    pub fn new(base_addr: usize) -> PL011Uart {
        PL011Uart { base_addr }
    }

    /// Returns a pointer to the register block
    fn ptr(&self) -> *const RegisterBlock {
        self.base_addr as *const _
}
```

This enables you to access the registers like in the following, not needing manual dereference on each access and the `unsafe` keyword is already encapsulated as well:
```rust
self.DR.set(c)
```

Maybe you'll find it useful.

In case that during your project, you encounter any place where you find a lack of generic embedded infrastructure crates, feel free to drop us a note.
We're always interested in what the real world needs.

**Comment by rminnich** [comment]
This is fantastic. We will give this a try. Thanks!

**Comment by andre-richter** [comment]
:+1:
