### ISSUE TITLE
Cleanup Branches and Tags

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#442]
Delete all the branches and tags which were carried over from coreboot.

The only branches we need to keep are the `main` branch and possibly some development branches.

**Comment by orangecms** [comment]
I just went and cleaned up a bunch of branches, old ones and those which had been merged, leaving a few only. 🌱 
I see 4.x tags from coreboot only; I'll just remove them all in the coming days. 🧹

**Comment by orangecms** [comment]
Done, tags removed. :sparkles:
