### ISSUE TITLE
Re-enable RISC-V QEMU Tests in CI

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#443]
See the `exit 0` skip here: https://github.com/oreboot/oreboot/blob/main/azure-pipelines.yml#L133

These CI checks were disabled because they re-build QEMU from source each time which added an unnecessary 8 minutes to the tests. Instead, we should be using a pre-built QEMU or caching the build.

**Comment by derpsteb** [comment]
Could use [this](https://github.com/actions/cache) caching action. 
Would requiring adding another step to the job. Then the other jobs could check if there is a cache hit before running.
Initial ideas for a cache-key could be: The built binary or the Makefile. Both only exist if at least one build has run. The Makefile potentially wouldn't catch version changes.

**Comment by orangecms** [comment]
Note: We have switched to GitHub Actions; now see
https://github.com/oreboot/oreboot/blob/main/.github/workflows/fsp-qemu.yml#L72
