### ISSUE TITLE
Poll: Is it "oreboot", "Oreboot" or "OreBoot"?

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#445]
Add an emoji with your vote:

* :rocket: for "oreboot"
* :heart: for "Oreboot"
* :tada: for "OreBoot"

**Comment by rminnich** [comment]
when does the poll close

**Comment by ArthurHeymans** [comment]
With coreboot, it was decided that it should always be full lowercase for trademark reasons. IANAL, so I comment on the validity of that decision. However if you start a phrase with a lowercase letter it looks like you made an typo. If that trademark reason is a thing and if you have to pick, I'd suggest at least going uppercase for the first letter as that is less confusing.

**Comment by rjoleary** [comment]
> when does the poll close

Let's close it in about a week.

**Comment by rjoleary** [comment]
Could this be another option: lowercase except at the beginning of a sentence?

**Comment by rjoleary** [comment]
The poll is closed. The final results are:

* 11 for "oreboot"
* 5 for "Oreboot"
