### ISSUE TITLE
Measure unit test coverage in CI

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#447]
There are some instructions on setting this up for Azure Pipelines here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results

Documentation from the Rust compiler: https://doc.rust-lang.org/beta/unstable-book/compiler-flags/instrument-coverage.html

**Comment by gogo2464** [comment]
I want to be assigned for this issue.

I have more epxerience with travis-ci than azure devops (tough I learn it at school). Can I use it instead?

**Comment by gogo2464** [comment]
I saw an azure code. Then I requested a Request Free Parallelism to azure devops. I will use azure devops.

**Comment by gogo2464** [comment]
@rjoleary , @rminnich  ready for a review. Check  https://github.com/oreboot/oreboot/pull/537

**Comment by gogo2464** [comment]
As told in this PR https://github.com/oreboot/oreboot/pull/527#pullrequestreview-847016588 we migrated to travis ci/cd.

Merged! https://github.com/oreboot/oreboot/pull/537 Fell free to close this issue.
