### ISSUE TITLE
QEMU-FSP: Parse HOBs

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#450]
The FSP_MEMORY_INIT function returns a list of hand-off-blocks (HOB) as a `VOID **HobListPtr` parameter. Each HOB has a GUID and a struct associated with it.

For example, one of these HOBs is:

```
typedef struct {
 EFI_HOB_GENERIC_HEADER Header;
 EFI_GUID Owner;
 EFI_RESOURCE_TYPE ResourceType;
 EFI_RESOURCE_ATTRIBUTE_TYPE ResourceAttribute;
 EFI_PHYSICAL_ADDRESS PhysicalStart;
 UINT64 ResourceLength;
} EFI_HOB_RESOURCE_DESCRIPTOR;
```

The data in these HOBs becomes important for creating E820 tables, ACPI tables, etc...

See the https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/fsp-architecture-spec-v2.pdf spec for details.

**Comment by jhand2** [comment]
@aquadara is going to start looking into this as well

**Comment by aquadara** [comment]
With PR #488 we're at least parsing these and printing them out. It could definitely be prettier, and I believe we wanted to pull this stuff into a library anyway (right now it's just inline in main.rs). But the tables are at least walked and their contents seem reasonable enough when printed.
