### ISSUE TITLE
QEMU-FSP: Use the SplitFspBin.py tool instead of `git apply`

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#452]
Currently, inside the `firsttime_fsp` recipe of the main Makefile, we `git apply` a patch onto fspsdk to change the FSP_BASE address. This only work because we re-compile the QEMU-FSP from source.

Instead, we should use the SplitFspBin.py Python program to relocate the FSP binary to a new base after it is compiled. See: https://github.com/universalpayload/fspsdk/blob/qemu_fsp_x64/IntelFsp2Pkg/Tools/SplitFspBin.py

**Comment by aquadara** [comment]
I believe PR #482 (to rebase) and PR #484 to (to split thereafter) addressed this - closing out.
