### ISSUE TITLE
Use rustsbi for SBI support for Risc-v

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#461]
@orangecms pointed us at: https://github.com/rustsbi/rustsbi

This is an implementation of SBI in Rust. We think we can compile it with the rest of oreboot and run from M-Mode.

**Comment by orangecms** [comment]
We have pulled it in for the Nezha board now.

See `src/mainboard/sunxi/nezha/sbi/`.

**Comment by orangecms** [comment]
Considering this done for now. We may be able to factor a few things out at some point. :-)
