### ISSUE TITLE
FSP QEMU Targets conflict during parallel builds

### ISSUE THREAD

**Issue by jhand2** [oreboot/oreboot#494]
The QEMU FSP build outputs to the same directory regardless of architecture. This causes conflicts during a multithreaded build where both targets are built. Need to rework this build to output to different directories.

**Comment by orangecms** [comment]
We have switched to Cargo workspace and parked most of the QEMU targets in `src.broken`.

We'll do better next time. Closing this now as it's currently not applicable.
