### ISSUE TITLE
Oreboot doesn't match Coreboot's features

### ISSUE THREAD

**Issue by vqs0214** [oreboot/oreboot#613]
Hello, we are trying to port Oreboot on a custom RISCV board and we have already ported Coreboot. We expected Oreboot to match Coreboot in functionality and execution flow, which doesn't seem to be the case. It looks like Oreboot runs the bootblock stage and directly loads the payload without loading intermediate stages namely ROMSTAGE and RAMSTAGE unlike Coreboot. We do see some platforms that run a romstage() function in the bootblock but it still doesn't load those stages from the cbfs. In addition, we do not see any support for cbfs compression either. 

Are there plans to add these functionalities in the future?

**Comment by orangecms** [comment]
Closing now as there is no further feedback. Thank you!
