### ISSUE TITLE
Address deprecation of Node.js 12 in CI Actions

### ISSUE THREAD

**Issue by bwerthmann** [oreboot/oreboot#626]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

https://github.com/oreboot/oreboot/actions/runs/3371817811

---
Initial Thinking:

- [x] #631
- [ ] #632

**Comment by bwerthmann** [comment]
Looks like I missed one:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: codecov/codecov-action

**Comment by orangecms** [comment]
Whoopsies! 80/20? :D
