### ISSUE TITLE
Prune `probot-auto-merge` from Oreboot Project

### ISSUE THREAD

**Issue by bwerthmann** [oreboot/oreboot#652]
These must be done by someone with high privileges in this project. AFAIK that's @rminnich and maybe @orangecms.

- [ ] Remove `probot-auto-merge` from <https://github.com/oreboot/oreboot/settings/access>
- [x] Remove `probot-auto-merge` from <https://github.com/oreboot/oreboot/settings/installations>
- [x] Remove `automerge` label from <https://github.com/oreboot/oreboot/issues/labels>

**Comment by orangecms** [comment]
I cannot find anything under access, the other two are done.

**Comment by bwerthmann** [comment]
Good enough for me.
