### ISSUE TITLE
Configure Oreboot Project Settings to replace `probot-auto-merge` functionality

### ISSUE THREAD

**Issue by bwerthmann** [oreboot/oreboot#655]
These must be done by someone with high privileges in this project. AFAIK that's @rminnich and maybe @orangecms.

- [x] Enable [Allow auto-merge](<https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#managing-auto-merge>) is enabled in Oreboot Project Settings
- [x] Enable [`Automatically delete head branches`](<https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches>)

Test Plan:

- [x] A `Contributor` (@bwerthmann) may [Enable auto-merge](<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge>) on a PR
  - [x] It should allow @bwerthmann to set auto-merge on a PR
  - [ ] It should delete the branch once PR is merged. This may not work across forks?
- [ ] Same for @rminnich and/or @orangecms

**Comment by orangecms** [comment]
Adjusting settings is done, thank you! 🥳

I'll also remove the automerge tag to rid folks of confusion.

**Comment by bwerthmann** [comment]
This worked for me.
