### ISSUE TITLE
Setup system to allow end-users to configure the build

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#67]
Coreboot has kconfig and "make menuconfig". This provides UI to discover and change build settings.

Right now for oreboot, we use [conditional compilation](https://doc.rust-lang.org/1.30.0/book/first-edition/conditional-compilation.html) to select which drivers to include. This does not seem to extend far beyond turning features on/off.

For example, we need a mechanism for the end-user to specify a path to the kernel they want to include.

**Comment by rjoleary** [comment]
@sphinxc0re I set you as the assignee since you had a bunch of ideas on this topic.

**Comment by pickfire** [comment]
Maybe we can combine conditional compilation with environment variables which allow us to set the paths for some particular configuration?

But I wonder if conditional compilation could have constrains embedded in it like how coreboot does. Like determining the hierarchy of configuration.

**Comment by orangecms** [comment]
We have started using xtask as a build framework, passing on build options to e.g. opt into SBI for sunxi/nezha (to be generalized for RISC-V) as well aa the payload.

**Comment by orangecms** [comment]
Having come a long way, we now offer the first build options, including DRAM size for the JH7110 (StarFive VisionFive 2, Milk-V Mars, ...).

**Comment by orangecms** [comment]
For thr DRAM size, I included build-time checks. It errors when provided unsupported values.

Closing this as complete now.
