### ISSUE TITLE
why bt0 called main stage twice in nezha project？

### ISSUE THREAD

**Issue by Mammon-github** [oreboot/oreboot#683]
Hi！In the end of main function in bt0, there is some code below:
`    println!("Run payload at 0x{:x}", RAM_BASE);`
`.   unsafe {`
`       let f: unsafe extern "C" fn() = transmute(RAM_BASE);`
`       f();`
`   }`
i think it makes the cpu jump to the main stage and never return,  but the main function returns the same address(RAM_BASE). And finish function will call the main stage again. Is it a kind of insurance or something else？

**Comment by orangecms** [comment]
Hi, that is mostly leftovers from different design approaches and hasn't been cleaned up yet. Feel free to file a pull request :)

**Comment by Mammon-github** [comment]
ok，thanks
