### ISSUE TITLE
Use llvm objcopy instead of gcc objcopy

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#80]
Wouldn't it make more sense to use the llvm objcopy because we're using the llvm objcopy?

**Comment by andre-richter** [comment]
For reference: https://github.com/rust-embedded/cargo-binutils

**Comment by andre-richter** [comment]
Cool thing is, you can then invoke the llvm binutils using your custom Rist target.json, e.g.:

https://github.com/rust-embedded/rust-raspi3-OS-tutorials/blob/master/11_exceptions_groundwork/Makefile#L78-L79

(Not needed for objcopy though).

**Comment by rjoleary** [comment]
Thanks, it works really well!
